theme: jekyll-theme-minimal
title: INFORMS Journal on Computing
description: A site for hosting software and data repositories associated with papers appearing in the INFORMS Journal on Computing
logo: logos/INFORMS-Journal-on-Computing_large.png
